# Generated by Django 3.2.5 on 2021-07-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_auto_20210724_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivekind',
            name='language',
            field=models.CharField(choices=[('ru', 'по-русски'), ('en', 'по-английски')], max_length=2),
        ),
    ]
