# Generated by Django 3.2.5 on 2021-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0009_auto_20211015_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivethematic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
