# Generated by Django 3.2.5 on 2021-10-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0011_rename_mandatoryelectiveforstudentgroup_mandatoryelectiveinstudentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='text_teachers',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='elective',
            name='max_number_students',
            field=models.PositiveIntegerField(default=255),
        ),
    ]
