# Generated by Django 3.2.5 on 2021-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0020_elective_english_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentonelective',
            name='priority',
        ),
        migrations.AlterField(
            model_name='elective',
            name='english_description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='elective',
            name='english_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
