# Generated by Django 3.2.5 on 2021-12-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0021_auto_20211203_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentonelective',
            name='next_priority_application',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_priority_application', to='electives.studentonelective'),
        ),
    ]
