# Generated by Django 3.2.5 on 2022-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0028_auto_20220131_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivethematic',
            name='short_name',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creditunitskind',
            name='short_name',
            field=models.CharField(max_length=2),
        ),
    ]
