# Generated by Django 3.2.5 on 2022-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0029_auto_20220416_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindofelective',
            name='exam_possibility',
            field=models.CharField(choices=[('+', 'Only with the exam'), ('-', 'Only without the exam'), ('+-', 'With the exam or without the exam')], max_length=2),
        ),
    ]
