# Generated by Django 3.2.5 on 2022-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0031_alter_kindofelective_exam_possibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentonelective',
            name='attached',
        ),
        migrations.AddField(
            model_name='studentonelective',
            name='potential',
            field=models.BooleanField(default=True),
        ),
    ]
