# Generated by Django 3.2.5 on 2021-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210927_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='max_cs_courses_autumn',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='max_cs_courses_spring',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='max_light_credit_unit_autumn',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='max_light_credit_unit_spring',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_number_of_exams_autumn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_number_of_exams_spring',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='min_number_of_exams_autumn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='min_number_of_exams_spring',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
