---
common:
  k8s_master_uri: https://35.228.93.184
  k8s_ca_base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRWCtvM0pneVZDb2htMVhZbWZJVmROVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSaE1qRTFOVE5sWVMwelpUVTBMVFJrWmprdE9XTmxaUzAzWXpBeFpXUXpNR0UxWW1FdwpIaGNOTWpBd01URXlNRGMwTWpRM1doY05NalV3TVRFd01EZzBNalEzV2pBdk1TMHdLd1lEVlFRREV5UmhNakUxCk5UTmxZUzB6WlRVMExUUmtaamt0T1dObFpTMDNZekF4WldRek1HRTFZbUV3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURFb1YzeDJLN2hQY0tGWUdwWGQ0d05YS2ZrWUhBZ3kxV1RMMW1uL2dYRwpzbjI0OUFzZzNGbXBVYlZWeTRoRjdBSjJYTHlIQlNaQ1Y5MG93UXRHQnF0R3JLeXkvdURMU1Q4RHZoNjRidFNYCi9pWjhXaDhONDRmTkhOZ3ErNGlObnhUL1hqRm0xMlRaWVlldnA1L0VoY2lFZVRDY3hUSm12YWhaVEdjaG5maUwKVTJiN0svZHMwZ0tEbE1YVWtGL3dTdXVJWmpZL1gwUXhHdTJBNVUrMEdTcGM3VGpOQ3g3VFpmSVlKeExuWmplRgpiakh5T0E1RmNvcVQycE11VnVudG4ycVNFc2NwZWMzdzh4azN5eFo1MHpRQWhmNTBoSEJFdWNrSjIveS9MbkovCk94YWtxWTJIQ2FuTm1KWUl0YUNKZk9JVno2bWh3L1d1UmFKQVJoQmQ3SzNmQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBdQpBOVIvdlo3blJzbU95UlBCbVdqOFo5eHlHUnRFTEF2ekhPMWFHVjhEc3dqU3F2OFFkNWxNeWVSWU81UWwyMkF2CkJYOWFDY0VJUFg4VDQrRE96T1p1MW9HVWxjWGNBM1dJN3pUVWx1QmNBcWM0UHdhaGdsTHlhZnU3cjJEZ2crckoKS3dMZTd5VUpPOGZiK0M2TTJRbEoxQ3dQV2h4d1ZzNExYYzZHcHlKaUtQdi9LMkJuVlJIb3VNNUE4SFJ1K01xTApsT0FhWmhYb1F4WnJMR3Y2NmhKdWJpMnN3bElJaTVMYk5WbThza1AvZGxwcE00bFk0d2hIbWUrV0tGSHM4VjJFCmNNQTRvbEJISDJ2WDF5dkk4eGhQbU96QmlxZWhZRE5zWkhTNEhUbXluSVlvRlorUUJMV01FdzhoNFU4VXlsV28KY0JwdVF4bDRKVVhGb0EvcEpObUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  k8s_token: "{{ env='K8S_TOKEN' }}"
  k8s_namespace: emkn 

europe-north1:
  app_name: emkn
  app_port: 8000

  image_path: europe-north1-docker.pkg.dev/itk8s-208609/emkn/server
  image_version: "{{ env='BUILD_NUMBER' }}"

  static_image_path: europe-north1-docker.pkg.dev/itk8s-208609/emkn/static
  static_image_version: "{{ env='BUILD_NUMBER' }}"

  database_secret: emkn-prod-creds

  replicas_count: 1

  templates:
    - template: ^server/.*.yaml.j2
    - template: ^static/.*.yaml.j2
    - template: ^ingress.yaml.j2