# Generated by Django 3.2.5 on 2022-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_url', models.URLField(default='https://users.math-cs.spbu.ru/~okhotin/course_process/course_announcement_autumn2021.html')),
                ('english_url', models.URLField(default='https://users.math-cs.spbu.ru/~okhotin/course_process/course_announcement_autumn2021_en.html')),
                ('google_form_url', models.URLField(default='https://docs.google.com/forms/d/12X4uaBPgNszp0DQ6juW8n9LP4b5jV4ro5TujiGngy-g/')),
                ('block_fall', models.BooleanField(default=False)),
            ],
        ),
    ]
