# Generated by Django 3.2.5 on 2022-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_thematickey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThematicKey',
        ),
    ]
