# Generated by Django 3.2.5 on 2022-04-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_delete_thematickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='block_fall_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='block_spring_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='show_google_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='show_slack_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='show_student_names',
            field=models.BooleanField(default=True),
        ),
    ]
