# Generated by Django 3.2.5 on 2022-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_key',
            field=models.CharField(default='1~2Me9b5.EgVHQlw4OADyrKZxN3GiTtSWfaYqJRh', max_length=100),
        ),
    ]
