# Generated by Django 3.2.5 on 2022-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invitation_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_key',
            field=models.CharField(default='DLt_hNA.ReYQ6m5djxzCIOSlyoU7k02a3WfGMcvZ', max_length=100),
        ),
    ]
