# Generated by Django 3.2.5 on 2022-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_invitation_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_key',
            field=models.CharField(default='m5uP81Dy97TEOZdNtYaCXr3QFgI~2nMoBGk_l-jH', max_length=100),
        ),
    ]
