# Generated by Django 3.2.5 on 2022-04-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_invitation_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_key',
            field=models.CharField(default='n5JX0CQyuA4Z-7HfiRBT2qKcO~tFhaIN681UxY.E', max_length=100),
        ),
    ]
