# Generated by Django 3.2.5 on 2021-07-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electives', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheronelective',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person'),
        ),
        migrations.AddField(
            model_name='studentonelective',
            name='elective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.elective'),
        ),
        migrations.AddField(
            model_name='studentonelective',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.person'),
        ),
        migrations.AddField(
            model_name='elective',
            name='students',
            field=models.ManyToManyField(related_name='student_list', through='electives.StudentOnElective', to='users.Person'),
        ),
        migrations.AddField(
            model_name='elective',
            name='teachers',
            field=models.ManyToManyField(related_name='teaher_list', through='electives.TeacherOnElective', to='users.Person'),
        ),
    ]
