# Generated by Django 3.2.5 on 2021-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivekind',
            name='credit_units',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Seminar'), (3, 'Small course'), (4, 'Big course')]),
        ),
    ]
