# Generated by Django 3.2.5 on 2021-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_alter_electivekind_credit_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivekind',
            name='credit_units',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Семинар'), (3, 'Малый'), (4, 'Большой')]),
        ),
        migrations.AlterField(
            model_name='electivekind',
            name='language',
            field=models.CharField(choices=[('RU', 'russian'), ('EN', 'english')], max_length=2),
        ),
    ]
