# Generated by Django 3.2.5 on 2021-07-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('electives', '0002_studentonelectve_teacheronelectve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentOnElectve',
            new_name='StudentOnElective',
        ),
        migrations.RenameModel(
            old_name='TeacherOnElectve',
            new_name='TeacherOnElective',
        ),
        migrations.AddField(
            model_name='elective',
            name='students',
            field=models.ManyToManyField(related_name='student_list', through='electives.StudentOnElective', to='users.Person'),
        ),
        migrations.AddField(
            model_name='elective',
            name='teachers',
            field=models.ManyToManyField(related_name='teaher_list', through='electives.TeacherOnElective', to='users.Person'),
        ),
    ]
