# Generated by Django 3.2.5 on 2021-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_auto_20210717_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
