# Generated by Django 3.2.5 on 2021-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('electives', '0003_auto_20210717_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentonelective',
            old_name='with_examenation',
            new_name='with_examination',
        ),
        migrations.AddField(
            model_name='elective',
            name='codename',
            field=models.CharField(default='Code', max_length=100),
        ),
        migrations.AlterField(
            model_name='elective',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_list', through='electives.TeacherOnElective', to='users.Person'),
        ),
    ]
