# Generated by Django 3.2.5 on 2021-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0004_alter_electivekind_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivekind',
            name='language',
            field=models.CharField(choices=[('ru', 'на русском'), ('en', 'на английском')], max_length=2),
        ),
    ]
