# Generated by Django 3.2.5 on 2021-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0004_auto_20210722_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='codename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
