# Generated by Django 3.2.5 on 2021-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0006_auto_20210826_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='max_number_students',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
