# Generated by Django 3.2.5 on 2021-10-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0007_alter_elective_max_number_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveThematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='elective',
            name='thematic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electives.electivethematic'),
        ),
    ]
