# Generated by Django 3.2.5 on 2021-10-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20211014_2339'),
        ('electives', '0008_auto_20211014_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentonelective',
            name='is_necessary',
        ),
        migrations.CreateModel(
            name='MandatoryElectiveForStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.elective')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroup')),
            ],
        ),
    ]
