# Generated by Django 3.2.5 on 2021-10-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20211014_2339'),
        ('electives', '0010_alter_electivethematic_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MandatoryElectiveForStudentGroup',
            new_name='MandatoryElectiveInStudentGroup',
        ),
    ]
