# Generated by Django 3.2.5 on 2021-10-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0013_alter_elective_text_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentonelective',
            name='kind',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='electives.electivekind'),
        ),
    ]
