# Generated by Django 3.2.5 on 2021-11-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0014_studentonelective_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentonelective',
            name='attached',
            field=models.BooleanField(default=False),
        ),
    ]
