# Generated by Django 3.2.5 on 2021-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0015_studentonelective_attached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elective',
            name='teachers',
        ),
        migrations.AddField(
            model_name='elective',
            name='english_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
