# Generated by Django 3.2.5 on 2021-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0016_auto_20211120_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivethematic',
            name='english_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
