# Generated by Django 3.2.5 on 2021-11-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0017_electivethematic_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivethematic',
            name='english_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
