# Generated by Django 3.2.9 on 2021-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0019_alter_elective_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='english_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
