# Generated by Django 3.2.5 on 2021-12-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('electives', '0022_studentonelective_next_priority_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_root', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_from_fall', to='electives.studentonelective')),
                ('maybe_fall_root', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_from_maybe_fall', to='electives.studentonelective')),
                ('maybe_spring_root', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_from_maybe_spring', to='electives.studentonelective')),
                ('spring_root', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_from_spring', to='electives.studentonelective')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications_root', to='users.person')),
            ],
        ),
    ]
