# Generated by Django 3.2.5 on 2021-12-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0023_applicationsroot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentonelective',
            name='next_priority_application',
        ),
        migrations.AddField(
            model_name='studentonelective',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
