# Generated by Django 3.2.5 on 2021-12-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20211014_2339'),
        ('electives', '0024_auto_20211204_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryThematicInStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.studentgroup')),
                ('thematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.electivethematic')),
            ],
        ),
        migrations.RemoveField(
            model_name='mandatoryelectiveinstudentgroup',
            name='elective',
        ),
        migrations.RemoveField(
            model_name='mandatoryelectiveinstudentgroup',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='teacheronelective',
            name='elective',
        ),
        migrations.RemoveField(
            model_name='teacheronelective',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ApplicationsRoot',
        ),
        migrations.DeleteModel(
            name='MandatoryElectiveInStudentGroup',
        ),
        migrations.DeleteModel(
            name='TeacherOnElective',
        ),
    ]
