# Generated by Django 3.2.5 on 2022-01-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0027_auto_20211218_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'на русском'), ('en', 'на английском')], default='ru', max_length=2)),
                ('credit_units', models.PositiveSmallIntegerField(choices=[(2, 'Семинар'), (3, 'Малый'), (4, 'Большой')], default=4)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'осенний'), (2, 'весенний')], default=1)),
                ('attached', models.BooleanField(default=False)),
                ('count_of_applications', models.PositiveIntegerField(default=0)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_counters', to='electives.elective')),
                ('thematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_counters', to='electives.electivethematic')),
            ],
        ),
    ]
