# Generated by Django 3.2.5 on 2022-01-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('electives', '0028_applicationcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcounter',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electives.electivekind'),
        ),
        migrations.AlterField(
            model_name='studentonelective',
            name='elective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='electives.elective'),
        ),
        migrations.AlterField(
            model_name='studentonelective',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.person'),
        ),
    ]
