# Generated by Django 3.2.5 on 2022-01-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0029_auto_20220117_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcounter',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.electivekind'),
        ),
    ]
