# Generated by Django 3.2.5 on 2021-07-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='min_number_of_exams_authumn',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='min_number_of_exams_spring',
            field=models.SmallIntegerField(default=1),
        ),
    ]
