# Generated by Django 3.2.5 on 2021-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210717_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='min_number_of_exams_spring',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='max_number_of_exams_spring',
            field=models.SmallIntegerField(default=1),
        ),
    ]
