# Generated by Django 3.2.5 on 2021-09-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210927_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='max_number_of_exams_autumn',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='min_number_of_exams_spring',
            field=models.SmallIntegerField(default=1),
        ),
    ]
