# Generated by Django 3.2.5 on 2021-12-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0005_auto_20211014_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='users.person')),
                ('student_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.studentgroup')),
            ],
        ),
    ]
