# Generated by Django 3.2.5 on 2021-12-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0006_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='max_credit_unit_autumn',
            new_name='max_credit_unit_fall',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='max_cs_courses_autumn',
            new_name='max_cs_courses_fall',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='max_light_credit_unit_autumn',
            new_name='max_light_credit_unit_fall',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='max_number_of_exams_autumn',
            new_name='max_number_of_exams_fall',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='min_credit_unit_autumn',
            new_name='min_credit_unit_fall',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='min_number_of_exams_autumn',
            new_name='min_number_of_exams_fall',
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_data', to='users.person'),
        ),
    ]
