# Generated by Django 3.2.5 on 2021-12-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20211204_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='max_credit_unit_fall',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_credit_unit_spring',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_cs_courses_fall',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_cs_courses_spring',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_light_credit_unit_fall',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_light_credit_unit_spring',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_number_of_exams_fall',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='max_number_of_exams_spring',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='min_credit_unit_fall',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='min_credit_unit_spring',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='min_number_of_exams_fall',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='min_number_of_exams_spring',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
