name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      shell: bash
      env: 
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
        SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
      run: |
        python manage.py test
